#!/bin/sh
SCRIPT_DIR=$( cd -- "$( dirname -- "$0" )" &> /dev/null && pwd )
ROOT_DIR=$( cd -- "$SCRIPT_DIR/.." &> /dev/null && pwd )

exec 2>&1
exec $ROOT_DIR/victron_smartevse -envfile $ROOT_DIR/smartevse.env
